title: A Shady Place
author:
  name: GitHub User
  email: your-email@domain.com
description: >
  Portfolio, Unreal Tutorials, and various interests.

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { icon: "github", title: "GitHub", url: "https://github.com/lucasfisher0" }
    - { icon: "linkedin", title: "LinkedIn", url: "https://www.linkedin.com/in/lucas-fisher-0aa347135/" }
  show_excerpts: true

# Build settings
#baseurl: /minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-toc

sass:
  quiet_deps: true
  silence_deprecations: [import]
